qemu-system-x86_64 -smp 6 -m 8192 \
	-nographic -serial mon:stdio  --enable-kvm -cpu host\
	-kernel Linux_compiled/arch/x86_64/boot/bzImage \
	-append "root=/dev/sda2 rw console=ttyS0" \
	-hda ./ubuntu_20g.img \
	-drive file=./ext4.swap,format=raw \
	-drive file=./sdc.img,format=raw \
	-drive id=nvme0,if=none,format=qcow2,file=./exe.img \
	-device nvme,drive=nvme0,serial=000,max_ioqpairs=16 \
	-drive id=nvme1,if=none,format=qcow2,file=./ext4.qcow2 \
	-device nvme,drive=nvme1,serial=001,max_ioqpairs=16 \
	-drive id=nvme2,if=none,format=qcow2,file=./ext2.qcow2 \
	-device nvme,drive=nvme2,serial=002,max_ioqpairs=16 \
	-net user,hostfwd=::2222-:22 -net nic
